baseurl = "http://pkimes.github.io/"

publishDir = "../pkimes.github.io"

title = "pkimes"

googleAnalytics = ""

defaultContentLanguage = "en"
hasCJKLanguage = true

sectionPagesMenu = "main"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "CSS", "RSS", "search" ]
  section = [ "HTML", "RSS" ]

[outputFormats.search]
  baseName = "search"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[languages]
[languages.en]
  languageName = "English"
  weight = 1

# allow raw html
[markup.goldmark.renderer]
  unsafe = true